# Generated by Django 5.2.3 on 2025-06-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Изображения')),
                ('stock', models.IntegerField(default=0, verbose_name='Количество на складе')),
            ],
            options={
                'verbose_name': 'Продукт магазина',
                'verbose_name_plural': 'Продукты магазина',
            },
        ),
    ]
