x = int(input("Введите число x: "))
a = int(input("Введите число a: "))
b = int(input("Введите число b: "))
c = int(input("Введите число c: "))

print(f'-1 / ( x ** 2 )')
print(f'a / ( b * c )')
print(f"a / ( b - c )")
print(f"( a + b ) / 2")
print(f" 5.45 * ( a + 2 * b ) / ( 2 - a )")
print(f" (-b + ( b * 2 - 4 * a * c) * 0.5 ) / ( 2 * a )")
print(f" ( -b + 1 / a ) / ( 2 / c )")
print(f" 1 / ( 1 + ( a + b ) / 2)")
print(f" 1 / ( 1 + 1 / ( 2 + 1 / ( 3 + 1 / 5 )))")
print(f" 2 * ( m * n )")