# Generated by Django 5.2.1 on 2025-05-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
