num1 = float(input("Введите первое число: "))
num2 = float(input("Введите второе число: "))
num3 = float(input("Введите третье число: "))
min_ch = min(num1, num2, num3)
max_ch = max(num1, num2, num3)
print("Минимальное значение: ", min_ch)
print("Максимальное значение: ", max_ch)
