# Generated by Django 5.2.3 on 2025-06-22 15:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('category', models.CharField(default='Общее', max_length=100, verbose_name='Категория')),
                ('image', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Изображения')),
                ('content', models.TextField(verbose_name='Полное содержание')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Пост блога',
                'verbose_name_plural': 'Посты блога',
                'ordering': ['-pub_date'],
            },
        ),
    ]
