# Generated by Django 5.1.7 on 2025-03-23 15:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
