# Generated by Django 5.1.7 on 2025-03-23 15:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_grade_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='name',
        ),
        migrations.AddField(
            model_name='grade',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
