# Generated by Django 5.1.7 on 2025-03-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_my_grade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='my_grade',
            new_name='main_grade',
        ),
    ]
