# Generated by Django 5.1.7 on 2025-03-24 10:35

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_my_grade_main_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main_grade',
            options={'ordering': ['-value'], 'verbose_name': 'Основная оценка', 'verbose_name_plural': 'Основные оценки'},
        ),
        migrations.RemoveField(
            model_name='main_grade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='main_grade',
            name='subject',
        ),
        migrations.AddField(
            model_name='main_grade',
            name='description',
            field=models.TextField(blank=True, help_text='Дополнительное описание оценки', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='main_grade',
            name='value',
            field=models.DecimalField(decimal_places=2, default=django.utils.timezone.now, help_text='Оценка от 0 до 100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Значение оценки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='main_grade',
            name='name',
            field=models.CharField(help_text='Введите название оценки/рейтинга', max_length=100, verbose_name='Название оценки'),
        ),
    ]
